spring:
  application:
    name: 'Yandex Eats Analogue'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/yandexEats_analogue'
    username: 'postgres'
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081